In [35]:
import numpy as np
    
class HierarchicalClustering:
    def __init__(self, n_clusters):
        self.n_clusters = n_clusters
        self.clusters = []
        self.labels = None

    def fit(self, X):
        # Dane jako klastry
        self.clusters = [[i] for i in range(len(X))]

        # Pętla, która będzie się robiła do momentu wystarczającej liczby klastrów
        while len(self.clusters) > self.n_clusters:
            # Szukanie najbliższych klastrów
            min_dist = math.inf
            min_pair = None
            for i in range(len(self.clusters)):
                for j in range(i+1, len(self.clusters)):
                    dist = self._distance(X, self.clusters[i], self.clusters[j])
                    if dist < min_dist:
                        min_dist = dist
                        min_pair = (i, j)

            # Łączenie najbliższych klastrów
            c1, c2 = min_pair
            self.clusters[c1] = self.clusters[c1] + self.clusters[c2]
            self.clusters.pop(c2)

        # Przydzielanie indeksów do przykładów
        self.labels = np.zeros(len(X))
        for i, cluster in enumerate(self.clusters):
            for j in cluster:
                  self.labels[j] = i

    def _distance(self, X, c1, c2):
        # Obliczenie średniej odległości pomiędzy punktami w klastrach
        sum_dist = 0
        for i in c1:
            for j in c2:
                sum_dist += np.linalg.norm(X[i] - X[j])
        return sum_dist / (len(c1) * len(c2))

In [96]:
import math
# Wygenerowane dane
X = np.random.rand(40, 3)

# Definiujemy klastrowanie i dopasowujemy je do danych
model = HierarchicalClustering(n_clusters=3)
model.fit(X)

# Predykcje do każdego klastera
predictions = model.labels

print(X)
print("Mój algorytm:", predictions)

from sklearn.cluster import AgglomerativeClustering

cluster = AgglomerativeClustering(n_clusters=3, affinity='euclidean', linkage='ward')
KF = cluster.fit_predict(X)
print("Sklearn:",KF)

[[0.33062056 0.49352531 0.37706571]
 [0.84022863 0.9433765  0.45110308]
 [0.06778111 0.46511258 0.28044528]
 [0.61333617 0.32337358 0.3838258 ]
 [0.04330183 0.87714008 0.15472099]
 [0.26473988 0.51937159 0.74749152]
 [0.17774094 0.47603375 0.73555224]
 [0.04474517 0.37177174 0.80635072]
 [0.59211675 0.99062164 0.76852836]
 [0.63196422 0.59268291 0.88834472]
 [0.03373503 0.44327488 0.19508304]
 [0.23178572 0.37613573 0.72198261]
 [0.82552943 0.66387068 0.12864791]
 [0.11791185 0.60493572 0.24976486]
 [0.78818761 0.64956284 0.16206547]
 [0.20009272 0.0608154  0.44483509]
 [0.72097385 0.89561858 0.17583946]
 [0.17711943 0.33393121 0.16220992]
 [0.57897331 0.9139346  0.20258408]
 [0.16999702 0.67009056 0.43673661]
 [0.47361829 0.44415861 0.65589951]
 [0.19447298 0.39746944 0.51588434]
 [0.60437054 0.17845083 0.36249205]
 [0.51609179 0.11953037 0.39612703]
 [0.37450382 0.95224757 0.5847794 ]
 [0.91588639 0.30683355 0.14530964]
 [0.18366445 0.26309833 0.29656376]
 [0.20430899 0.1565501  0.90

In [97]:
from sklearn import metrics

HierarchicalClustering_label = predictions
print(HierarchicalClustering_label)

KF_label = KF
print(KF_label)

acc_HierarchicalClustering = metrics.rand_score(KF_label, HierarchicalClustering_label)

print("Dokładność prewidywania klasy w procentach:", acc_HierarchicalClustering)

[0. 1. 0. 2. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 1. 0. 1. 0. 1. 0. 1. 0. 2. 2.
 1. 2. 0. 0. 2. 1. 0. 2. 0. 0. 2. 1. 1. 2. 1. 1.]
[0 1 0 2 0 0 0 0 0 2 0 0 1 0 1 2 1 0 1 0 0 0 2 2 0 1 0 0 2 2 0 2 0 0 2 0 0
 2 1 1]
Dokładność prewidywania klasy w procentach: 0.7461538461538462
