In [121]:
import numpy as np
    
class HierarchicalClustering:
    def __init__(self, n_clusters):
        self.n_clusters = n_clusters
        self.clusters = []
        self.labels = None

    def fit(self, X):
        # Dane jako klastry
        self.clusters = [[i] for i in range(len(X))]

        # Pętla, która będzie się robiła do momentu wystarczającej liczby klastrów
        while len(self.clusters) > self.n_clusters:
            # Szukanie najbliższych klastrów
            min_dist = math.inf
            min_pair = None
            for i in range(len(self.clusters)):
                for j in range(i+1, len(self.clusters)):
                    dist = self._distance(X, self.clusters[i], self.clusters[j])
                    if dist < min_dist:
                        min_dist = dist
                        min_pair = (i, j)

            # Łączenie najbliższych klastrów
            c1, c2 = min_pair
            self.clusters[c1] = self.clusters[c1] + self.clusters[c2]
            self.clusters.pop(c2)

        # Przydzielanie indeksów do przykładów
        self.labels = np.zeros(len(X))
        for i, cluster in enumerate(self.clusters):
            for j in cluster:
                  self.labels[j] = i

    def _distance(self, X, c1, c2):
        # Obliczenie średniej odległości pomiędzy punktami w klastrach
        sum_dist = 0
        for i in c1:
            for j in c2:
                sum_dist += np.linalg.norm(X[i] - X[j])
        return sum_dist / (len(c1) * len(c2))

In [127]:
import math
# Wygenerowane dane
X = np.random.rand(40, 3)

In [128]:
# Definiujemy klastrowanie i dopasowujemy je do danych
model = HierarchicalClustering(n_clusters=3)
model.fit(X)

# Predykcje do każdego klastera
predictions = model.labels

print(X)
print("Mój algorytm:", predictions)

from sklearn.cluster import AgglomerativeClustering

cluster = AgglomerativeClustering(n_clusters=3, affinity='euclidean', linkage='ward')
KF = cluster.fit_predict(X)
print("Sklearn:",KF)

[[0.51423388 0.79309298 0.86118129]
 [0.17903499 0.27438154 0.21769764]
 [0.30979375 0.22722339 0.45000017]
 [0.3045697  0.84614821 0.06622308]
 [0.40291387 0.77085694 0.74068689]
 [0.79111271 0.42530086 0.80947197]
 [0.8765418  0.63612418 0.94418768]
 [0.62539499 0.35670318 0.3450881 ]
 [0.43756743 0.19055556 0.08656616]
 [0.92646911 0.42896599 0.63201561]
 [0.52268432 0.08898964 0.90874525]
 [0.34680428 0.81320754 0.58663602]
 [0.88676492 0.6921219  0.79802928]
 [0.71298306 0.85881376 0.84012634]
 [0.86461845 0.98894579 0.4627338 ]
 [0.41487082 0.38991125 0.95397964]
 [0.10669221 0.57431484 0.21488947]
 [0.70359688 0.53643496 0.6116206 ]
 [0.92975331 0.97739995 0.17021597]
 [0.80404848 0.79643574 0.20613783]
 [0.55306769 0.37093334 0.01309508]
 [0.03201154 0.31010747 0.01179023]
 [0.20925664 0.75613607 0.66387946]
 [0.26152181 0.41427229 0.67064807]
 [0.58193044 0.76244121 0.57056651]
 [0.61889817 0.69738418 0.33518551]
 [0.26260923 0.09823344 0.4824688 ]
 [0.23618989 0.39799847 0.76

In [131]:
from sklearn.metrics import silhouette_score
from sklearn import metrics

HierarchicalClustering_label = predictions
print(HierarchicalClustering_label)

KF_label = KF
print(KF_label)

agg_silhouette_score1 = silhouette_score(X, KF_label)
agg_silhouette_score2 = silhouette_score(X, HierarchicalClustering_label)
print("Silhouette score algorytmu z Sickit-learn:",agg_silhouette_score1)
print("Silhouette score mojego algorytmu:",agg_silhouette_score2)

[0. 1. 0. 1. 0. 0. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 0.
 0. 0. 0. 0. 0. 2. 0. 0. 1. 1. 1. 0. 2. 0. 0. 0.]
[0 1 0 1 0 2 2 2 1 2 0 0 2 2 2 0 1 2 2 2 1 1 0 0 2 2 0 0 0 0 2 2 2 1 1 2 0
 2 2 2]
Silhouette score algorytmu z Sickit-learn: 0.24932801137372945
Silhouette score mojego algorytmu: 0.19052731416204566
